[target.x86_64-pc-windows-msvc]
rustflags = [
    "-C",
    "target-feature=+crt-static",
    "-C",
    "link-arg=/OPT:REF,ICF",
]

[target.aarch64-pc-windows-msvc]
rustflags = [
    "-C",
    "target-feature=+crt-static",
    "-C",
    "link-arg=/OPT:REF,ICF",
]
